//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bar.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_BAR_H)
#define _BAR_H

#include "Menu.h"
#include "Barman.h"

class Bar {
public:
	Menu menu;
	Barman* barman;
	void zarejestrowacKlienta();
	void weryfikowacKarteLojalnosciowa();
	void zarezerwowacGre();
	void przyjacZamowienieNaCieplo();
	void przyjacZamowienieNaZimno();
	void rozliczyc();
	Bar(Menu menu, Barman barman);
};

#endif  //_BAR_H
