//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bar.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Bar.h"
#include "Menu.h"
#include "Barman.h"

void Bar::zarejestrowacKlienta() {

}

void Bar::weryfikowacKarteLojalnosciowa() {

}

void Bar::zarezerwowacGre() {

}

void Bar::przyjacZamowienieNaCieplo() {

}

void Bar::przyjacZamowienieNaZimno() {

}

void Bar::rozliczyc() {

}

Bar::Bar(Menu menu, Barman barman) {

}

