//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Barman.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_BARMAN_H)
#define _BARMAN_H


class Barman {
public:
	void przyjacZamowienie();
	void wydacZamowienie();
	void realizowacZamowienie();
	void rozliczycKlienta();
	void zarejestrowacKlienta();
	void sprawdzicWiek();
};

#endif  //_BARMAN_H
