//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Barman.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Barman.h"

void Barman::przyjacZamowienie() {

}

void Barman::wydacZamowienie() {

}

void Barman::realizowacZamowienie() {

}

void Barman::rozliczycKlienta() {

}

void Barman::zarejestrowacKlienta() {

}

void Barman::sprawdzicWiek() {

}

