//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BazaDanych.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "BazaDanych.h"
#include "HarmonogramRezerwacji.h"

void BazaDanych::zapiszKlienta() {

}

void BazaDanych::przypiszKarteDoKLienta() {

}

void BazaDanych::zapiszZmiany() {

}

BazaDanych::BazaDanych(HarmonogramRezerwacji harmonogram) {

}

