//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BazaDanych.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_BAZADANYCH_H)
#define _BAZADANYCH_H

#include "Klient.h"
#include "HarmonogramRezerwacji.h"

class BazaDanych {
public:
	Klient klienty;
	HarmonogramRezerwacji* harmonogram;
	void zapiszKlienta();
	void przypiszKarteDoKLienta();
	void zapiszZmiany();
	BazaDanych(HarmonogramRezerwacji harmonogram);
};

#endif  //_BAZADANYCH_H
