//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bilard.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Bilard.h"

Bilard::Bilard(harmonogramRezerwacji: HarmonogramRezerwacji, klientPrzyStole: Klient)() {

}

