//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bilard.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_BILARD_H)
#define _BILARD_H


class Bilard {
public:
	HarmonogramRezerwacji* harmonogram;
	int ograniczenieLiczbyOsobPrzyStole;
	Klient* klientPrzyStole;
	Bilard(harmonogramRezerwacji: HarmonogramRezerwacji, klientPrzyStole: Klient)();
};

#endif  //_BILARD_H
