//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HarmonogramRezerwacji.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "HarmonogramRezerwacji.h"

void HarmonogramRezerwacji::zarezerwowacGre() {

}

HarmonogramRezerwacji::HarmonogramRezerwacji(SlotCzasowy[12] listaSlotow) {

}

