//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HarmonogramRezerwacji.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_HARMONOGRAMREZERWACJI_H)
#define _HARMONOGRAMREZERWACJI_H

#include "SlotCzasowy.h"

class HarmonogramRezerwacji {
public:
	SlotCzasowy listaSlotow;
	void zarezerwowacGre();
	HarmonogramRezerwacji(SlotCzasowy[12] listaSlotow);
};

#endif  //_HARMONOGRAMREZERWACJI_H
