//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KartaLojalnosciowa.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_KARTALOJALNOSCIOWA_H)
#define _KARTALOJALNOSCIOWA_H

#include "Klient.h"

class KartaLojalnosciowa {
public:
	int bilansPunktow;
	Klient* klient;
	void dodajPunkty();
	KartaLojalnosciowa(Klient klient);
};

#endif  //_KARTALOJALNOSCIOWA_H
