//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KartaLojalnosciowa.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "KartaLojalnosciowa.h"
#include "Klient.h"

void KartaLojalnosciowa::dodajPunkty() {

}

KartaLojalnosciowa::KartaLojalnosciowa(Klient klient) {

}

