//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kasa.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_KASA_H)
#define _KASA_H

#include "BazaDanych.h"

class Kasa {
public:
	double schowekNaPieniadze;
	String terminal;
	BazaDanych* bazaDanych;
	void przetworzPlatnoscKarta();
	void przetworzPlatnoscGotowka();
	void naliczRabaty(int Karta lojalnosciowa*);
	boolean sprawdzCzyJestKartaLojalnosciowa();
	Kasa(BazaDanych bazaDanych);
};

#endif  //_KASA_H
