//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kasa.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Kasa.h"
#include "BazaDanych.h"

void Kasa::przetworzPlatnoscKarta() {

}

void Kasa::przetworzPlatnoscGotowka() {

}

void Kasa::naliczRabaty(int Karta lojalnosciowa*) {

}

boolean Kasa::sprawdzCzyJestKartaLojalnosciowa() {

}

Kasa::Kasa(BazaDanych bazaDanych) {

}

