//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_KLIENT_H)
#define _KLIENT_H


class Klient {
public:
	String godnosc;
	String numerTelefonu;
	String adresMailowy;
	KartaLojalnosciowa* kartaLojalnosciowa;
	void rezerwowac();
	void grac();
	void zamawiac();
	void zakonczycGreIWyjsc();
	Klient(String godnosc, String numerTelefonu, String adresMailowy);
};

#endif  //_KLIENT_H
