//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Klient.h"

void Klient::rezerwowac() {

}

void Klient::grac() {

}

void Klient::zamawiac() {

}

void Klient::zakonczycGreIWyjsc() {

}

Klient::Klient(String godnosc, String numerTelefonu, String adresMailowy) {

}

