//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kuchnia.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Kuchnia.h"
#include "Kucharz.h"

void Kuchnia::przyjacZamowienieNaCieplo() {

}

Kuchnia::Kuchnia(Kucharz kucharz) {

}

