//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kucharz.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "Kucharz.h"

void Kucharz::realizowacZamowienie() {

}

void Kucharz::wydacZamowienie() {

}

