//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kuchnia.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_KUCHNIA_H)
#define _KUCHNIA_H

#include "Kucharz.h"

class Kuchnia {
public:
	boolean stanOtwarcia;
	Kucharz* kucharz;
	void przyjacZamowienieNaCieplo();
	Kuchnia(Kucharz kucharz);
};

#endif  //_KUCHNIA_H
