//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kucharz.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_KUCHARZ_H)
#define _KUCHARZ_H


class Kucharz {
public:
	void realizowacZamowienie();
	void wydacZamowienie();
};

#endif  //_KUCHARZ_H
