//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_MENU_H)
#define _MENU_H


enum Menu {
	itemNaCieplo1,
	itemNaCieplo2,
	itemNaCieplo3,
	itemNaZimno1,
	itemNaZimno2,
	itemNaZimno3
};

#endif  //_MENU_H
