//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SlotCzasowy.h
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#if !defined(_SLOTCZASOWY_H)
#define _SLOTCZASOWY_H

#include "Klient.h"

class SlotCzasowy {
public:
	Klient* klient;
	int Dzien;
	timestamp Godziny;
	int Stoly;
	SlotCzasowy(Klient klient, int dzien, timestamp godziny, int stoly);
};

#endif  //_SLOTCZASOWY_H
