//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SlotCzasowy.cpp
//  @ Date : 06.05.2026
//  @ Author : 
//
//


#include "SlotCzasowy.h"
#include "Klient.h"

SlotCzasowy::SlotCzasowy(Klient klient, int dzien, timestamp godziny, int stoly) {

}

